services:
  server:
    container_name: sponsor-pulse-server
    image: sponsor-pulse-server
    build:
      context: ../..
      dockerfile: apps/server/Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
