# Allows contributors to self-assign issues by commenting "/take" on them.
# Adapted from SponsorBlock's take-action.yml.
name: Assign Issue to Contributor

on:
  issue_comment:

jobs:
  assign:
    name: Take an Issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to commenter
        uses: bdougie/take-action@28b86cd8d25593f037406ecbf96082db2836e928
        env:
          GITHUB_TOKEN: ${{ github.token }}
